version: "2"

linters:
  default: standard
  enable:
    - errorlint
    - gocyclo
    - misspell
    - nakedret
    - unconvert
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    gocyclo:
      min-complexity: 20
    nakedret:
      max-func-lines: 50
  exclusions:
    paths:
      - node_modules
      - third_party$
      - builtin$
      - examples$
