#!/usr/bin/env bun

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { mediaDurationSeconds, minClipSeconds } from './clip-duration.mjs';
import { changelogSectionNotes, parseChangelog } from './changelog-notes.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
const checkClips = process.argv.includes('--clips');

const phases = [
  {
    phase: 1,
    title: 'CLI core',
    seam: 'sopsdeck CLI',
    match: /^(get|set|del|run|identity|files|errorlog)/,
    names: /ErrorLog/,
  },
  {
    phase: 2,
    title: 'Browser app',
    seam: 'localhost HTTP',
    match: /^drive/,
  },
  {
    phase: 3,
    title: 'Git Review / Commit / Sync',
    seam: 'Git adapter',
    match: /^(commit|sync|review|history|restore)/,
  },
  {
    phase: 4,
    title: 'Recipients',
    seam: 'CLI recipients / re-encrypt',
    match: /^recipient/,
    names: /Recipient|Teammate/,
  },
  {
    phase: 5,
    title: 'GitHub Publish',
    seam: 'GitHub Publish adapter',
    match: /^publish/,
    names: /Publish|GitHub/,
  },
  {
    phase: 6,
    title: 'Scan hook',
    seam: 'scan hook',
    match: /^scan/,
    names: /Scan/,
  },
  {
    phase: 7,
    title: 'Paste + MCP',
    seam: 'MCP',
    match: /^(mcp|set_paste)/,
    names: /MCP|Stdin/,
  },
];

const uncovered = [{ phase: 8, title: 'Public npm release', seam: 'release artifacts' }];

function testdox(name) {
  const body = name.replace(/^Test/, '');
  return body
    .replaceAll(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .replaceAll(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replaceAll('_', ' ')
    .replaceAll(/\s+/g, ' ')
    .trim();
}

function goTests() {
  const tests = [];
  function walk(dir) {
    for (const ent of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
      a.name.localeCompare(b.name),
    )) {
      const path = join(dir, ent.name);
      if (ent.isDirectory()) {
        walk(path);
        continue;
      }
      if (!ent.name.endsWith('_test.go')) continue;
      const src = readFileSync(path, 'utf8');
      for (const match of src.matchAll(/^func (Test[A-Za-z0-9_]+)\(/gm)) {
        tests.push({ file: ent.name, name: match[1], title: testdox(match[1]) });
      }
    }
  }
  walk(join(root, 'internal'));
  return tests;
}

function classifyGo(test) {
  const named = phases.find((phase) => phase.names?.test(test.name));
  if (named) {
    return named;
  }

  const base = test.file.replace(/_test\.go$/, '');
  return phases.find((phase) => phase.match.test(base));
}

function featuresMarkdown(go) {
  const lines = [
    '# Features proved by tests',
    '',
    'Generated by `./scripts/docs`. Do not edit by hand.',
    '',
    'These names are the living specification of behavior that currently has a test.',
    'Domain words come from [CONTEXT.md](../CONTEXT.md).',
    '',
    '## CLI',
    '',
  ];
  for (const test of go) {
    lines.push(`- ${test.title} (\`${test.name}\`)`);
  }
  lines.push('');
  return `${lines.join('\n')}`;
}

function seamsMarkdown(go) {
  const lines = [
    '# Public seams',
    '',
    'Generated by `./scripts/docs`. Do not edit by hand.',
    '',
    'Seams are from [Lock public test seams and delivery phases](../.scratch/sopsdeck-product/issues/15-lock-public-test-seams-and-delivery-phases.md).',
    'A phase is covered when at least one test exercises that seam.',
    '',
    '| Phase | Slice | Seam | Tests |',
    '| --- | --- | --- | --- |',
  ];

  const goByPhase = new Map();
  for (const test of go) {
    const phase = classifyGo(test);
    if (!phase) continue;
    const list = goByPhase.get(phase.phase) ?? [];
    list.push(test.name);
    goByPhase.set(phase.phase, list);
  }

  lines.push(
    `| 1 | CLI core | sopsdeck CLI | ${(goByPhase.get(1) ?? []).join(', ') || '_none_'} |`,
  );
  lines.push(
    `| 2 | Browser app | localhost HTTP | ${(goByPhase.get(2) ?? []).join(', ') || '_none_'} |`,
  );
  lines.push(
    `| 3 | Git Commit / Sync | Git adapter | ${(goByPhase.get(3) ?? []).join(', ') || '_none_'} |`,
  );
  lines.push(
    `| 4 | Recipients | CLI recipients / re-encrypt | ${(goByPhase.get(4) ?? []).join(', ') || '_none_'} |`,
  );
  lines.push(
    `| 5 | GitHub Publish | GitHub Publish adapter | ${(goByPhase.get(5) ?? []).join(', ') || '_none_'} |`,
  );
  lines.push(`| 6 | Scan hook | scan hook | ${(goByPhase.get(6) ?? []).join(', ') || '_none_'} |`);
  lines.push(`| 7 | Paste + MCP | MCP | ${(goByPhase.get(7) ?? []).join(', ') || '_none_'} |`);
  for (const row of uncovered) {
    lines.push(`| ${row.phase} | ${row.title} | ${row.seam} | _none_ |`);
  }
  lines.push('');
  return `${lines.join('\n')}`;
}

function loadCatalog() {
  return JSON.parse(readFileSync(join(root, 'docs/assets/catalog.json'), 'utf8'));
}

function assetsMarkdown(catalog) {
  const lines = [
    '# Product assets',
    '',
    'Generated by `./scripts/docs` from [catalog.json](assets/catalog.json). Stills, clips, and CLI demos come from `./scripts/demo` and `./scripts/cli-video.mjs`. Do not screenshot by hand.',
    '',
    '## Walkthrough',
    '',
    `Full studio path (open, edit, save, commit, Sync, grant Access, Publish): [${catalog.walkthrough}](assets/${catalog.walkthrough})`,
    '',
    '## Stills and clips',
    '',
    '| Action | Still | Clip |',
    '| --- | --- | --- |',
  ];
  for (const item of catalog.items) {
    lines.push(
      `| ${item.title} | ![${item.title}](assets/${item.still}) | [${item.clip}](assets/${item.clip}) |`,
    );
  }

  const casts = catalogCasts(catalog);
  if (casts.length > 0) {
    lines.push('', '## CLI casts', '');
    lines.push(
      'Recorded from the real local `sopsdeck` binary. Castkit-rendered MP4s and Asciinema v2 `.cast` files.',
      '',
      '| Command | Cast | Video |',
      '| --- | --- | --- |',
    );
    for (const item of casts) {
      lines.push(
        `| ${item.title} | [${item.cast}](assets/${item.cast}) | ${item.video ? `[${item.video}](assets/${item.video})` : ''} |`,
      );
    }
  }

  lines.push('');
  return `${lines.join('\n')}`;
}

function catalogCasts(catalog) {
  return catalog.cli ?? [];
}

function requiredAssetFiles(catalog) {
  const files = catalog.items.flatMap((item) => [
    `docs/assets/${item.still}`,
    `docs/assets/${item.clip}`,
  ]);
  files.push(`docs/assets/${catalog.walkthrough}`);
  for (const item of catalogCasts(catalog)) {
    files.push(`docs/assets/${item.cast}`);
    if (item.video) files.push(`docs/assets/${item.video}`);
  }
  files.push(...publicAssetFiles(catalog).map((name) => `site/public/assets/${name}`));

  return files;
}

function publicAssetFiles(catalog) {
  return [
    'catalog.json',
    catalog.walkthrough,
    ...catalog.items.flatMap((item) => [item.still, item.clip]),
    ...catalogCasts(catalog).map((item) => item.cast),
    ...catalogCasts(catalog).flatMap((item) => (item.video ? [item.video] : [])),
  ];
}

function unlinkedAssets(catalog) {
  const roots = [
    'README.md',
    'docs/README.md',
    'docs/assets.md',
    'site/src/pages/index.astro',
    'site/src/pages/docs/index.astro',
    'docs/guide.md',
  ];
  const combined = roots
    .map((rel) => {
      try {
        return readFileSync(join(root, rel), 'utf8');
      } catch {
        return '';
      }
    })
    .join('\n');
  const missing = [];
  for (const name of [
    catalog.walkthrough,
    ...catalog.items.flatMap((item) => [item.still, item.clip]),
    ...catalogCasts(catalog).map((item) => item.cast),
    ...catalogCasts(catalog).flatMap((item) => (item.video ? [item.video] : [])),
  ]) {
    if (!combined.includes(name)) missing.push(name);
  }

  return missing;
}

function appVersion() {
  const src = readFileSync(join(root, 'internal/version/version.go'), 'utf8');
  const match = /const Version = "([^"]+)"/.exec(src);
  if (!match) {
    throw new Error('internal/version/version.go: missing Version');
  }

  return match[1];
}

function whatsNewPayload(md, version) {
  const parsed = parseChangelog(md);
  const section =
    changelogSectionNotes(md, version) || parsed.find((item) => item.heading === 'Unreleased');
  const heading = section?.heading || 'Unreleased';
  const notes = section?.notes || [];
  return `${JSON.stringify({ version, heading, date: section?.date || '', notes }, null, 2)}\n`;
}

function checkVersionDrift(version, bundled) {
  const npmPkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version;
  for (const [name, got] of Object.entries({
    'package.json': npmPkg,
    'whats-new.json': bundled,
  })) {
    if (got !== version) {
      process.stderr.write(`version drift: ${name} is ${got}, Go is ${version}\n`);
      return true;
    }
  }

  return false;
}

const go = goTests();
const catalog = loadCatalog();
const changelogMd = readFileSync(join(root, 'CHANGELOG.md'), 'utf8');
const version = appVersion();
const featuresMd = featuresMarkdown(go);
const seamsMd = seamsMarkdown(go);
const assetsMd = assetsMarkdown(catalog);
const files = {
  'docs/features.md': featuresMd,
  'docs/seams.md': seamsMd,
  'docs/assets.md': assetsMd,
  'desktop/src/whats-new.json': whatsNewPayload(changelogMd, version),
};

let stale = false;
for (const [rel, body] of Object.entries(files)) {
  const path = join(root, rel);
  if (check) {
    let current = '';
    try {
      current = readFileSync(path, 'utf8');
    } catch {
      current = '';
    }
    if (current !== body) {
      process.stderr.write(`${rel} is stale; run ./scripts/docs\n`);
      stale = true;
    }
    continue;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body);
}

if (!check) {
  const publicAssets = join(root, 'site/public/assets');
  mkdirSync(publicAssets, { recursive: true });
  for (const name of publicAssetFiles(catalog)) {
    const source = join(root, 'docs/assets', name);
    if (existsSync(source)) copyFileSync(source, join(publicAssets, name));
  }
}

if (check) {
  for (const rel of requiredAssetFiles(catalog)) {
    if (!existsSync(join(root, rel))) {
      process.stderr.write(`${rel} is missing; run ./scripts/demo\n`);
      stale = true;
    }
  }

  for (const name of unlinkedAssets(catalog)) {
    process.stderr.write(`${name} is not referenced in README, docs, or the landing page\n`);
    stale = true;
  }

  const bundled = JSON.parse(files['desktop/src/whats-new.json']).version;
  if (checkVersionDrift(version, bundled)) stale = true;

  if (checkClips) {
    for (const rel of clipAssetFiles(catalog)) {
      const path = join(root, rel);
      if (!existsSync(path)) {
        continue;
      }

      const seconds = mediaDurationSeconds(path);
      if (!Number.isFinite(seconds) || seconds < minClipSeconds) {
        process.stderr.write(
          `${rel} is ${Number.isFinite(seconds) ? `${seconds.toFixed(3)}s` : 'unreadable'}; want ≥ ${minClipSeconds}s. Re-record with ./scripts/demo\n`,
        );
        stale = true;
      }
    }
  }
}

function clipAssetFiles(catalog) {
  return [
    `docs/assets/${catalog.walkthrough}`,
    ...catalog.items.map((item) => `docs/assets/${item.clip}`),
    ...catalogCasts(catalog).map((item) => `docs/assets/${item.cast}`),
  ];
}

if (stale) {
  process.exit(1);
}
