#!/usr/bin/env bun

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { mediaDurationSeconds, minClipSeconds } from './clip-duration.mjs';
import { mdToHtml, sitePage } from './site-pages.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
const checkClips = process.argv.includes('--clips');

const phases = [
  {
    phase: 1,
    title: 'CLI core',
    seam: 'sopsdeck CLI',
    match: /^(get|set|del|run|identity|files)/,
  },
  {
    phase: 3,
    title: 'Git Review / Commit / Sync',
    seam: 'Git adapter',
    match: /^(commit|sync|review|history|restore)/,
  },
  {
    phase: 4,
    title: 'Recipients',
    seam: 'CLI recipients / re-encrypt',
    match: /^recipient/,
    names: /Recipient|Teammate/,
  },
  {
    phase: 5,
    title: 'GitHub Publish',
    seam: 'GitHub Publish adapter',
    match: /^publish/,
    names: /Publish|GitHub/,
  },
  {
    phase: 6,
    title: 'Scan hook',
    seam: 'scan hook',
    match: /^scan/,
    names: /Scan/,
  },
];

const uncovered = [
  { phase: 7, title: 'Paste + MCP', seam: 'MCP' },
  { phase: 8, title: 'Signed macOS release', seam: 'release artifacts' },
];

function testdox(name) {
  const body = name.replace(/^Test/, '');
  return body
    .replaceAll(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .replaceAll(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replaceAll('_', ' ')
    .replaceAll(/\s+/g, ' ')
    .trim();
}

function rustDox(name) {
  return name.replaceAll('_', ' ');
}

function goTests() {
  const tests = [];
  function walk(dir) {
    for (const ent of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
      a.name.localeCompare(b.name),
    )) {
      const path = join(dir, ent.name);
      if (ent.isDirectory()) {
        walk(path);
        continue;
      }
      if (!ent.name.endsWith('_test.go')) continue;
      const src = readFileSync(path, 'utf8');
      for (const match of src.matchAll(/^func (Test[A-Za-z0-9_]+)\(/gm)) {
        tests.push({ file: ent.name, name: match[1], title: testdox(match[1]) });
      }
    }
  }
  walk(join(root, 'internal'));
  return tests;
}

function rustTests() {
  const tests = [];
  const dir = join(root, 'desktop/src-tauri/src');
  for (const file of readdirSync(dir).sort()) {
    if (!file.endsWith('.rs')) continue;
    const src = readFileSync(join(dir, file), 'utf8');
    for (const match of src.matchAll(/#\[test]\s*\n\s*fn ([a-z0-9_]+)/g)) {
      tests.push({ file, name: match[1], title: rustDox(match[1]) });
    }
  }
  return tests;
}

function classifyGo(test) {
  const named = phases.find((phase) => phase.names?.test(test.name));
  if (named) {
    return named;
  }

  const base = test.file.replace(/_test\.go$/, '');
  return phases.find((phase) => phase.match.test(base));
}

function featuresMarkdown(go, rust) {
  const lines = [
    '# Features proved by tests',
    '',
    'Generated by `./scripts/docs`. Do not edit by hand.',
    '',
    'These names are the living specification of behavior that currently has a test.',
    'Domain words come from [CONTEXT.md](../CONTEXT.md).',
    '',
    '## CLI',
    '',
  ];
  for (const test of go) {
    lines.push(`- ${test.title} (\`${test.name}\`)`);
  }
  lines.push('', '## Desktop discovery', '');
  if (rust.length === 0) {
    lines.push('- _none yet_');
  } else {
    for (const test of rust) {
      lines.push(`- ${test.title} (\`${test.name}\`)`);
    }
  }
  lines.push('');
  return `${lines.join('\n')}`;
}

function seamsMarkdown(go, rust) {
  const lines = [
    '# Public seams',
    '',
    'Generated by `./scripts/docs`. Do not edit by hand.',
    '',
    'Seams are from [Lock public test seams and delivery phases](../.scratch/sopsdeck-product/issues/15-lock-public-test-seams-and-delivery-phases.md).',
    'A phase is covered when at least one test exercises that seam.',
    '',
    '| Phase | Slice | Seam | Tests |',
    '| --- | --- | --- | --- |',
  ];

  const goByPhase = new Map();
  for (const test of go) {
    const phase = classifyGo(test);
    if (!phase) continue;
    const list = goByPhase.get(phase.phase) ?? [];
    list.push(test.name);
    goByPhase.set(phase.phase, list);
  }

  const rustNames = rust.map((test) => test.name).join(', ') || '_none_';
  lines.push(
    `| 1 | CLI core | sopsdeck CLI | ${(goByPhase.get(1) ?? []).join(', ') || '_none_'} |`,
  );
  lines.push(`| 2 | Tauri folder-first editor | Managed File discovery | ${rustNames} |`);
  lines.push(
    `| 3 | Git Commit / Sync | Git adapter | ${(goByPhase.get(3) ?? []).join(', ') || '_none_'} |`,
  );
  lines.push(
    `| 4 | Recipients | CLI recipients / re-encrypt | ${(goByPhase.get(4) ?? []).join(', ') || '_none_'} |`,
  );
  lines.push(
    `| 5 | GitHub Publish | GitHub Publish adapter | ${(goByPhase.get(5) ?? []).join(', ') || '_none_'} |`,
  );
  lines.push(`| 6 | Scan hook | scan hook | ${(goByPhase.get(6) ?? []).join(', ') || '_none_'} |`);
  for (const row of uncovered) {
    lines.push(`| ${row.phase} | ${row.title} | ${row.seam} | _none_ |`);
  }
  lines.push('');
  return `${lines.join('\n')}`;
}

function loadCatalog() {
  return JSON.parse(readFileSync(join(root, 'docs/assets/catalog.json'), 'utf8'));
}

function assetsMarkdown(catalog) {
  const lines = [
    '# Product assets',
    '',
    'Generated by `./scripts/docs` from [catalog.json](assets/catalog.json). Stills, clips, and CLI casts come from `./scripts/demo`. Do not screenshot by hand.',
    '',
    '## Walkthrough',
    '',
    `Full studio path (open, edit, save, commit, Sync, grant Access, Publish): [${catalog.walkthrough}](assets/${catalog.walkthrough})`,
    '',
    '## Stills and clips',
    '',
    '| Action | Still | Clip |',
    '| --- | --- | --- |',
  ];
  for (const item of catalog.items) {
    lines.push(
      `| ${item.title} | ![${item.title}](assets/${item.still}) | [${item.clip}](assets/${item.clip}) |`,
    );
  }

  const casts = catalogCasts(catalog);
  if (casts.length > 0) {
    lines.push('', '## CLI casts', '');
    lines.push(
      'Recorded by `./scripts/demo` from real `sopsdeck` against copies of testdata. Asciinema v2 `.cast` files.',
      '',
      '| Command | Cast |',
      '| --- | --- |',
    );
    for (const item of casts) {
      lines.push(`| ${item.title} | [${item.cast}](assets/${item.cast}) |`);
    }
  }

  lines.push('');
  return `${lines.join('\n')}`;
}

function catalogCasts(catalog) {
  return catalog.cli ?? [];
}

function requiredAssetFiles(catalog) {
  const files = catalog.items.flatMap((item) => [
    `docs/assets/${item.still}`,
    `docs/assets/${item.clip}`,
  ]);
  files.push(`docs/assets/${catalog.walkthrough}`);
  files.push('site/assets/editor.png');
  for (const item of catalogCasts(catalog)) {
    files.push(`docs/assets/${item.cast}`);
  }

  return files;
}

function unlinkedAssets(catalog) {
  const roots = [
    'README.md',
    'docs/README.md',
    'docs/assets.md',
    'site/index.html',
    'site/docs/index.html',
    'site/docs/assets.html',
  ];
  const combined = roots
    .map((rel) => {
      try {
        return readFileSync(join(root, rel), 'utf8');
      } catch {
        return '';
      }
    })
    .join('\n');
  const missing = [];
  for (const name of [
    catalog.walkthrough,
    ...catalog.items.flatMap((item) => [item.still, item.clip]),
    ...catalogCasts(catalog).map((item) => item.cast),
  ]) {
    if (!combined.includes(name)) missing.push(name);
  }

  return missing;
}

function appVersion() {
  const src = readFileSync(join(root, 'internal/version/version.go'), 'utf8');
  const match = /const Version = "([^"]+)"/.exec(src);
  if (!match) {
    throw new Error('internal/version/version.go: missing Version');
  }

  return match[1];
}

function changelogSection(md, heading) {
  const lines = md.split('\n');
  let start = -1;
  for (const [i, raw] of lines.entries()) {
    const line = raw.trim();
    if (
      line === `## ${heading}` ||
      line.startsWith(`## ${heading} `) ||
      line.startsWith(`## [${heading}]`)
    ) {
      start = i;
      break;
    }
  }

  if (start < 0) return;
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i += 1) {
    if (lines[i].trim().startsWith('## ')) {
      end = i;
      break;
    }
  }

  return lines.slice(start, end).join('\n');
}

function changelogBullets(md, heading) {
  const body = changelogSection(md, heading);
  if (!body) return [];
  return body
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.startsWith('- '))
    .map((line) => line.slice(2).trim());
}

function escapeHtml(text) {
  return text
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function changelogPage(md) {
  const headings = [...md.matchAll(/^## (.+)$/gm)].map((match) => match[1]);
  const sections = headings.map((heading) => {
    const items = changelogBullets(md, heading);
    const bullets =
      items.length === 0
        ? '          <li>No notes.</li>'
        : items.map((item) => `          <li>${escapeHtml(item)}</li>`).join('\n');
    const kicker = heading === 'Unreleased' ? 'In development' : 'Release';
    const title = heading === 'Unreleased' ? 'Unreleased' : heading;
    return `      <section class="release">
        <p class="kicker">${escapeHtml(kicker)}</p>
        <h2>${escapeHtml(title)}</h2>
        <ol class="notes">
${bullets}
        </ol>
      </section>`;
  });
  return sitePage({
    title: 'Sopsdeck — notes',
    kicker: 'Changelog',
    heading: "What's new",
    lede: 'From <code>CHANGELOG.md</code>. Versioning is <a href="docs/versioning.html">Epoch SemVer</a>.',
    active: 'notes',
    base: '',
    body: sections.join('\n'),
  });
}

function stripFirstHeading(md) {
  return md.replace(/^# .+\n+/, '');
}

function markdownSitePage({ title, kicker, heading, lede, md }) {
  const html = mdToHtml(stripFirstHeading(md))
    .split('\n')
    .map((line) => (line ? `        ${line}` : line))
    .join('\n');
  return sitePage({
    title,
    kicker,
    heading,
    lede,
    active: 'docs',
    base: '../',
    body: html,
  });
}

function docsHubPage() {
  return sitePage({
    title: 'Sopsdeck — docs',
    kicker: 'Documentation',
    heading: 'What the product is, proved',
    lede: 'Living pages generated from tests, the asset catalog, and CHANGELOG.md.',
    active: 'docs',
    base: '../',
    body: `        <ul class="doc-index">
          <li><a href="features.html">Living features</a> — generated from test names. If a behavior is not named here, it is not specified by a test yet.</li>
          <li><a href="seams.html">Public seams</a> — where tests must live, and which delivery phases still have none.</li>
          <li><a href="assets.html">Product assets</a> — stills, clips, walkthrough, and CLI casts from <code>./scripts/demo</code>.</li>
          <li><a href="versioning.html">Versioning</a> — Epoch SemVer; CHANGELOG.md is canonical.</li>
          <li><a href="glossary.html">Domain language</a> — words from CONTEXT.md.</li>
          <li><a href="../changelog.html">Notes</a> — generated from CHANGELOG.md.</li>
        </ul>`,
  });
}

function whatsNewPayload(md, version) {
  let heading = version;
  let notes = changelogBullets(md, version);
  if (notes.length === 0) {
    heading = 'Unreleased';
    notes = changelogBullets(md, 'Unreleased');
  }

  return `${JSON.stringify({ version, heading, notes }, null, 2)}\n`;
}

function checkVersionDrift(version, bundled) {
  const tauri = JSON.parse(
    readFileSync(join(root, 'desktop/src-tauri/tauri.conf.json'), 'utf8'),
  ).version;
  const pkg = JSON.parse(readFileSync(join(root, 'desktop/package.json'), 'utf8')).version;
  const cargoMatch = /^version = "([^"]+)"/m.exec(
    readFileSync(join(root, 'desktop/src-tauri/Cargo.toml'), 'utf8'),
  );
  const cargo = cargoMatch ? cargoMatch[1] : '';
  for (const [name, got] of Object.entries({
    'tauri.conf.json': tauri,
    'desktop/package.json': pkg,
    'Cargo.toml': cargo,
    'whats-new.json': bundled,
  })) {
    if (got !== version) {
      process.stderr.write(`version drift: ${name} is ${got}, Go is ${version}\n`);
      return true;
    }
  }

  return false;
}

const go = goTests();
const rust = rustTests();
const catalog = loadCatalog();
const changelogMd = readFileSync(join(root, 'CHANGELOG.md'), 'utf8');
const version = appVersion();
const featuresMd = featuresMarkdown(go, rust);
const seamsMd = seamsMarkdown(go, rust);
const assetsMd = assetsMarkdown(catalog);
const files = {
  'docs/features.md': featuresMd,
  'docs/seams.md': seamsMd,
  'docs/assets.md': assetsMd,
  'site/changelog.html': changelogPage(changelogMd),
  'site/docs/index.html': docsHubPage(),
  'site/docs/features.html': markdownSitePage({
    title: 'Sopsdeck — features',
    kicker: 'Living spec',
    heading: 'Features proved by tests',
    lede: 'Generated from test names. If a behavior is not named here, it is not specified by a test yet.',
    md: featuresMd,
  }),
  'site/docs/seams.html': markdownSitePage({
    title: 'Sopsdeck — seams',
    kicker: 'Delivery',
    heading: 'Public seams',
    lede: 'Where tests must live, and which delivery phases still have none.',
    md: seamsMd,
  }),
  'site/docs/assets.html': markdownSitePage({
    title: 'Sopsdeck — assets',
    kicker: 'Catalog',
    heading: 'Product assets',
    lede: 'Stills, clips, walkthrough, and CLI casts from <code>./scripts/demo</code>.',
    md: assetsMd,
  }),
  'site/docs/versioning.html': markdownSitePage({
    title: 'Sopsdeck — versioning',
    kicker: 'Releases',
    heading: 'Versioning',
    lede: 'Epoch SemVer. CHANGELOG.md is the source of truth.',
    md: readFileSync(join(root, 'docs/versioning.md'), 'utf8'),
  }),
  'site/docs/glossary.html': markdownSitePage({
    title: 'Sopsdeck — domain language',
    kicker: 'Glossary',
    heading: 'Domain language',
    lede: 'Words from CONTEXT.md. Use these in tests, UI copy, and docs.',
    md: readFileSync(join(root, 'CONTEXT.md'), 'utf8'),
  }),
  'desktop/src/whats-new.json': whatsNewPayload(changelogMd, version),
};

let stale = false;
for (const [rel, body] of Object.entries(files)) {
  const path = join(root, rel);
  if (check) {
    let current = '';
    try {
      current = readFileSync(path, 'utf8');
    } catch {
      current = '';
    }
    if (current !== body) {
      process.stderr.write(`${rel} is stale; run ./scripts/docs\n`);
      stale = true;
    }
    continue;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body);
}

if (check) {
  for (const rel of requiredAssetFiles(catalog)) {
    if (!existsSync(join(root, rel))) {
      process.stderr.write(`${rel} is missing; run ./scripts/demo\n`);
      stale = true;
    }
  }

  for (const name of unlinkedAssets(catalog)) {
    process.stderr.write(`${name} is not referenced in README, docs, or the landing page\n`);
    stale = true;
  }

  const bundled = JSON.parse(files['desktop/src/whats-new.json']).version;
  if (checkVersionDrift(version, bundled)) stale = true;

  if (checkClips) {
    for (const rel of clipAssetFiles(catalog)) {
      const path = join(root, rel);
      if (!existsSync(path)) {
        continue;
      }

      const seconds = mediaDurationSeconds(path);
      if (!Number.isFinite(seconds) || seconds < minClipSeconds) {
        process.stderr.write(
          `${rel} is ${Number.isFinite(seconds) ? `${seconds.toFixed(3)}s` : 'unreadable'}; want ≥ ${minClipSeconds}s. Re-record with ./scripts/demo\n`,
        );
        stale = true;
      }
    }
  }
}

function clipAssetFiles(catalog) {
  return [
    `docs/assets/${catalog.walkthrough}`,
    ...catalog.items.map((item) => `docs/assets/${item.clip}`),
    ...catalogCasts(catalog).map((item) => `docs/assets/${item.cast}`),
  ];
}

if (stale) {
  process.exit(1);
}
