#!/usr/bin/env bun

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');

const phases = [
  {
    phase: 1,
    title: 'CLI core',
    seam: 'sopsdeck CLI',
    match: /^(get|set|del|run|identity|files)/,
  },
  {
    phase: 3,
    title: 'Git Review / Commit / Sync',
    seam: 'Git adapter',
    match: /^(commit|sync)/,
  },
  {
    phase: 4,
    title: 'Recipients',
    seam: 'CLI recipients / re-encrypt',
    match: /^recipient/,
    names: /Recipient|Teammate/,
  },
  {
    phase: 5,
    title: 'GitHub Publish',
    seam: 'GitHub Publish adapter',
    match: /^publish/,
    names: /Publish|GitHub/,
  },
];

const uncovered = [
  { phase: 6, title: 'Scan hook', seam: 'scan hook' },
  { phase: 7, title: 'Paste + MCP', seam: 'MCP' },
  { phase: 8, title: 'Signed macOS release', seam: 'release artifacts' },
];

function testdox(name) {
  const body = name.replace(/^Test/, '');
  return body
    .replaceAll(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .replaceAll(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replaceAll('_', ' ')
    .replaceAll(/\s+/g, ' ')
    .trim();
}

function rustDox(name) {
  return name.replaceAll('_', ' ');
}

function goTests() {
  const tests = [];
  function walk(dir) {
    for (const ent of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
      a.name.localeCompare(b.name),
    )) {
      const path = join(dir, ent.name);
      if (ent.isDirectory()) {
        walk(path);
        continue;
      }
      if (!ent.name.endsWith('_test.go')) continue;
      const src = readFileSync(path, 'utf8');
      for (const match of src.matchAll(/^func (Test[A-Za-z0-9_]+)\(/gm)) {
        tests.push({ file: ent.name, name: match[1], title: testdox(match[1]) });
      }
    }
  }
  walk(join(root, 'internal'));
  return tests;
}

function rustTests() {
  const tests = [];
  const dir = join(root, 'desktop/src-tauri/src');
  for (const file of readdirSync(dir).sort()) {
    if (!file.endsWith('.rs')) continue;
    const src = readFileSync(join(dir, file), 'utf8');
    for (const match of src.matchAll(/#\[test]\s*\n\s*fn ([a-z0-9_]+)/g)) {
      tests.push({ file, name: match[1], title: rustDox(match[1]) });
    }
  }
  return tests;
}

function classifyGo(test) {
  const named = phases.find((phase) => phase.names?.test(test.name));
  if (named) {
    return named;
  }

  const base = test.file.replace(/_test\.go$/, '');
  return phases.find((phase) => phase.match.test(base));
}

function featuresMarkdown(go, rust) {
  const lines = [
    '# Features proved by tests',
    '',
    'Generated by `./scripts/docs`. Do not edit by hand.',
    '',
    'These names are the living specification of behavior that currently has a test.',
    'Domain words come from [CONTEXT.md](../CONTEXT.md).',
    '',
    '## CLI',
    '',
  ];
  for (const test of go) {
    lines.push(`- ${test.title} (\`${test.name}\`)`);
  }
  lines.push('', '## Desktop discovery', '');
  if (rust.length === 0) {
    lines.push('- _none yet_');
  } else {
    for (const test of rust) {
      lines.push(`- ${test.title} (\`${test.name}\`)`);
    }
  }
  lines.push('');
  return `${lines.join('\n')}`;
}

function seamsMarkdown(go, rust) {
  const lines = [
    '# Public seams',
    '',
    'Generated by `./scripts/docs`. Do not edit by hand.',
    '',
    'Seams are from [Lock public test seams and delivery phases](../.scratch/sopsdeck-product/issues/15-lock-public-test-seams-and-delivery-phases.md).',
    'A phase is covered when at least one test exercises that seam.',
    '',
    '| Phase | Slice | Seam | Tests |',
    '| --- | --- | --- | --- |',
  ];

  const goByPhase = new Map();
  for (const test of go) {
    const phase = classifyGo(test);
    if (!phase) continue;
    const list = goByPhase.get(phase.phase) ?? [];
    list.push(test.name);
    goByPhase.set(phase.phase, list);
  }

  const rustNames = rust.map((test) => test.name).join(', ') || '_none_';
  lines.push(
    `| 1 | CLI core | sopsdeck CLI | ${(goByPhase.get(1) ?? []).join(', ') || '_none_'} |`,
  );
  lines.push(`| 2 | Tauri folder-first editor | Managed File discovery | ${rustNames} |`);
  lines.push(
    `| 3 | Git Commit / Sync | Git adapter | ${(goByPhase.get(3) ?? []).join(', ') || '_none_'} |`,
  );
  lines.push(
    `| 4 | Recipients | CLI recipients / re-encrypt | ${(goByPhase.get(4) ?? []).join(', ') || '_none_'} |`,
  );
  lines.push(
    `| 5 | GitHub Publish | GitHub Publish adapter | ${(goByPhase.get(5) ?? []).join(', ') || '_none_'} |`,
  );
  for (const row of uncovered) {
    lines.push(`| ${row.phase} | ${row.title} | ${row.seam} | _none_ |`);
  }
  lines.push('');
  return `${lines.join('\n')}`;
}

const go = goTests();
const rust = rustTests();
const files = {
  'docs/features.md': featuresMarkdown(go, rust),
  'docs/seams.md': seamsMarkdown(go, rust),
};

let stale = false;
for (const [rel, body] of Object.entries(files)) {
  const path = join(root, rel);
  if (check) {
    let current = '';
    try {
      current = readFileSync(path, 'utf8');
    } catch {
      current = '';
    }
    if (current !== body) {
      process.stderr.write(`${rel} is stale; run ./scripts/docs\n`);
      stale = true;
    }
    continue;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body);
}

if (stale) {
  process.exit(1);
}
